version: '3.8'

services:
   db:
      image: mysql:5.6
      container_name: appsDB
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: helloworld


   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db


